### PR TITLE
Fine-tune the Qute benchmark

### PR DESCRIPTION
**Pull request by mkouba**
- use a generated value resolver
- use a "computed property"

This should make the comparison a little bit more fair because Qute is primarily designed to work with Quarkus where we generate some stuff during the build.

### CODE REVIEW

**Comment by mkouba** [comment]
FTR in quarkus 3.5+, there is a [patch](https://github.com/quarkusio/quarkus/pull/35916) related to some JDK problems that improves the performance significantly  in some benchmarks even by ~ 30%).

**Comment by fercomunello** [comment]
Great job, very interesting @mkouba! 

* Do you think it's viable to create an official **JTE extension** for Quarkus like this [Vert.x one](https://github.com/vert-x3/vertx-web/blob/master/vertx-template-engines/vertx-web-templ-jte/src/main/java/io/vertx/ext/web/templ/jte/impl/JteTemplateEngineImpl.java)? 
* And what kind of _stuff_ is generated during the Quarkus build for Qute?

Actually I don't see JTE as a replacement for Qute, they just have different purpouses I believe: 
* With Qute I can do general templating like emails not just web pages and also improves the code quality since it's very well integrated with Quarkus;
* And compiled JTE it almost looks like pre-compiled JSPs so the rendering performance is very high (_few CPU usage_) specially for heavy web pages & [hypermedia sytems](https://hypermedia.systems/). 

Really appreciate your work, we're talking about this on [Twitter](https://twitter.com/fercomunello/status/1728160192007671996) btw..

**Comment by mkouba** [comment]
> Great job, very interesting @mkouba!
> 
>  Do you think it's viable to create an official **JTE extension** for Quarkus like this [Vert.x one](https://github.com/vert-x3/vertx-web/blob/master/vertx-template-engines/vertx-web-templ-jte/src/main/java/io/vertx/ext/web/templ/jte/impl/JteTemplateEngineImpl.java)?

For sure. You can [propose a new Quarkiverse extension](https://github.com/quarkiverse/quarkiverse/wiki#getting-an-extension-onboarded). There's already the [quarkus-freemarker](https://github.com/quarkiverse/quarkus-freemarker) extension maintained by the community. 

> 
>  And what kind of _stuff_ is generated during the Quarkus build for Qute?

So in Qute the main things that we do during the build are (a) validations (e.g. the template structure and the optional type-safe parts of a template) and (b) generation of optimized value resolvers (i.e. components that know how to resolve properties of Java classes).

> 
> 
> Actually I don't see JTE as a replacement for Qute, they just have different purpouses I believe:
> 
> With Qute I can do general templating like emails not just web pages and also improves the code quality since it's very well integrated with Quarkus;
> 
> And compiled JTE it almost looks like pre-compiled JSPs so the rendering performance is very high (_few CPU usage_) specially for heavy web pages & [hypermedia sytems](https://hypermedia.systems/).
> 
> 
> Really appreciate your work, we're talking about this on [Twitter](https://twitter.com/fercomunello/status/1728160192007671996) btw..

It seems that this post was removed ;-).

**Comment by fercomunello** [comment]
@mkouba Thanks for the clarification! I'm doing some htmx projects using Jakarta MVC currently but soon I'll make a Quarkus version too that's I pretend to build a JTE extension as far as possible.

The tweet was deleted to avoid duplicating the same question as here (forgot to update, sorry about that). 
Link of the [thread](https://twitter.com/agoncal/status/1660723129071575071).

**Comment by mkouba** [comment]
Closing - there's no interest in merging :shrug:.

**Pull request closed without merging**
